apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app7
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/thanhdinh01/demo-argo1.git
    targetRevision: HEAD
    path: src
  destination:
    server: https://27.71.17.221:6443
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      prune: true
